Modules/Developer-Edition: New - Dev version for Pro.
elementor/elementor-dev pull request #23
Opened 2020-12-14 14:23 UTC by Nevoss

ref: ED-600

2020-12-18 11:41 UTC, matipojo requested changes

2020-12-18 11:41 UTC, matipojo commented on bootstrap.php
Fix according to the rename to `elementor-beta`.

2020-12-22 10:19 UTC, matipojo approved these changes

2020-12-22 10:24 UTC, matipojo requested changes

2020-12-22 10:24 UTC, matipojo commented on modules/developer-edition/version-control.php
> +		$current_version = $this->get_plugin_version( Bootstrap::ELEMENTOR_PLUGIN_NAME );
Adapt to work with the pro plugin. (add a filter to `get_wp_org_data` in order to allow the pro plugin to set its  stable version)

2021-01-05 19:06 UTC, matipojo requested changes

2021-01-05 19:06 UTC, matipojo commented on tests/phpunit/unit/modules/developer-edition/test-pro-version-control.php
> +	public function test_add_dev_param_to_get_version_request__when_elementor_pro_is_installed() {
```suggestion
	public function test_add_dev_param_to_get_version_request__when_elementor_pro_is_not_installed() {
```

2021-01-07 08:59 UTC, matipojo requested changes

2021-01-07 08:59 UTC, matipojo commented on tests/phpunit/unit/mocks/api.php
> +	const STORE_URL = 'https://api.test.com';
```suggestion
	const STORE_URL = 'https://api.test.local';
```

2021-01-07 18:00 UTC, matipojo approved these changes

2021-01-11 18:45 UTC, KingYes approved these changes

2021-01-11 18:45 UTC, merged