New: Docs - Version update logic
elementor/elementor-dev pull request #28
Opened 2021-04-28 14:56 UTC by Nevoss

ref: ED-2302

2021-05-04 10:11 UTC, StyleShit requested changes

2021-05-04 10:11 UTC, StyleShit commented on docs/README.md
> +Elementor Beta (Developer Edition) has responsibility for some UI changes that make the plugin look bit different from the stable version of Elementor.
```suggestion
Elementor Beta (Developer Edition) also adds some UI changes which makes the plugin look a bit different from the stable version of Elementor.
```

2021-05-04 13:41 UTC, StyleShit requested changes

2021-05-04 13:41 UTC, StyleShit commented on docs/README.md
> +Elementor Beta (Developer Edition) also adds for some UI changes which makes the plugin look a bit different from the stable version of Elementor.
```suggestion
Elementor Beta (Developer Edition) also adds some UI changes which makes the plugin look a bit different from the stable version of Elementor.
```

2021-05-04 13:41 UTC, StyleShit commented on docs/README.md
> +Elementor Beta (Developer Edition) also adds for some UI changes which makes the plugin look a bit different from the stable version of Elementor.
My bad..

2021-05-04 13:47 UTC, Nevoss commented on docs/README.md
> +Elementor Beta (Developer Edition) also adds for some UI changes which makes the plugin look a bit different from the stable version of Elementor.
I should have noticed it.

2021-05-04 14:04 UTC, StyleShit approved these changes

2021-05-24 17:34 UTC, matipojo requested changes

2021-05-24 17:34 UTC, matipojo commented on docs/README.md
> +The module "developer-edition" creates 2 instances of the classes `Core_Version_Control` and `Pro_Version_Control`, the main idea behind those classes is to interrupt the WordPress update mechanism a
```suggestion
The module "developer-edition" creates instances of the classes `Core_Version_Control` and `Pro_Version_Control`, the main idea behind those classes is to interrupt the WordPress update mechanism and make sure that the future updates of "Elementor" and "Elementor Pro" comes from the "dev" channel.
```

2021-05-24 17:34 UTC, matipojo commented on docs/README.md
> +The main difference between the 2 approaches is that in the Core version of Elementor the logic of which is the right version for the update determined in the plugin itself, while in the Pro version
```suggestion
The main difference between the 2 approaches is that in the Core version of Elementor the decision of which is the right version for the update is determined in the plugin itself, while in the Pro version of Elementor, the remote server has the responsibility to deliver the right version.
```

2021-06-03 11:39 UTC, merged